### ISSUE TITLE
对外提供软件仓库的公共账号

### ISSUE THREAD

**Issue by alick** [FZUG/Copr#2]
理想情况下，社区软件源应该有一个公共账号（或者名义账号），用于对外发布“稳定的”、“经过测试的”软件包。而现在 copr 的账户系统貌似是 FAS openid。不知道如何能做到这一点？（申请个公共邮箱去注册 FAS？感觉这样不大好吧。）

**Comment by tvvocold** [comment]
@1dot75cm

**Comment by sztsian** [comment]
我觉得应该看下copr的身份验证机制，然后从身份认证部分着手进行一些改造或者插件开发，从而实现所需的目的。

**Comment by 1dot75cm** [comment]
copr 正在调整服务器。这个问题等一切都稳定了，再逐步解决。
我考虑是社区人员在 copr 上打包，将稳定的包提交给“管理员”，“管理员”将经过测试的包发布 (http/ftp即可，不需其他附加服务)。
直接用 copr 也可以， copr 支持不使用 fas 验证。但这方面未进行进一步测试。

**Comment by alick9188** [comment]
嗯。HTTP 方式也可，只是可能需要写个脚本或手工维护。也可以测试下 copr 的非FAS认证机制。

**Comment by tvvocold** [comment]
@1dot75cm 
如果服务器不能建立，那就新建一个 FAS 吧。

**Comment by alick** [comment]
On 05/15/2015 12:38 PM, Ray wrote:
> @1dot75cm <https://github.com/1dot75cm>
> 如果服务器不能建立，那就新建一个 FAS 吧。
> 
新建个 FAS 公用？不是个好主意。

**Comment by tvvocold** [comment]
@alick 
绕过验证? 怎么使用/维护?

**Comment by alick** [comment]
上面提到的非FAS认证、或者HTTP方式服务

**Comment by tvvocold** [comment]
Talk is cheap.

**Comment by alick** [comment]
@1dot75cm 不知是否有时间研究下？

**Comment by 1dot75cm** [comment]
先http提供吧，就放在 copr-be.cloud.fdzh.org。
但ucloud真的不会停止服务么? @tvvocold
