### ISSUE TITLE
网页汉化问题

### ISSUE THREAD

**Issue by tvvocold** [FZUG/Copr#3]
大家看下哪里还需汉化吗?
e.g:
[API 页面](https://copr.fdzh.org/api/)
[license](https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#Good_Licenses)
...

**Comment by tvvocold** [comment]
@FZUG/tier1

**Comment by alick** [comment]
列举出的页面都没有太多可翻译的余地，也缺少翻译的必要性。

今后发issue时，尽量具体问题分别发。普通讨论可以发到列表等地方。

**Comment by tvvocold** [comment]
没有翻译余地和必要性？
好吧
