### ISSUE TITLE
Fedora 中文社区 Copr 构建系统内测邀请

### ISSUE THREAD

**Issue by tvvocold** [FZUG/Copr#4]
Hi there,

[Fedora 中文社区 Copr 构建系统](https://copr.fdzh.org)已开始内测！
我们诚挚地邀请您加入并 [反馈建议/Bug](https://github.com/FZUG/Copr/)。
您还可以邀请您的圈内朋友，或 [分享这一消息](http://www.fdzh.org/), 甚至 [帮助我们翻译!](https://github.com/FZUG/Copr/wiki) :blush:

Cheers,
Ray
fdzh.org

**Comment by tvvocold** [comment]
@FZUG/tier1 @FZUG/owners @wangjiezhe

**Comment by tvvocold** [comment]
@gbraad

**Comment by 1dot75cm** [comment]
^^~

**Comment by alick9188** [comment]
能不能讲的具体些，不然这样一个邀请帖不适合作为issue，因为根本不知道怎么才算issue被解决了。

**Comment by tvvocold** [comment]
@alick9188 内测完毕无Bug后不就可以Close吗?
 (鉴于邮件列表已经发过邀请了，这个贴目的是在Github上艾特打包者/或者圈内人士)

**Comment by alick9188** [comment]
那么这个Bug算不算Bug？(joke...)

下面是严肃的问题：内测计划什么时间点结束？内测期间发现/解决的Bug在哪里记录？

在 2015年3月13日 下午6:45，Ray <notifications@github.com>写道：

**Comment by tvvocold** [comment]
恩，经Bowen测试，编译多个kernel时后端会负载过大而崩溃，正在尝试修复。
（目前只是在和我hangouts里讲，应该可以/会公开到issues里吧...具体结束内测时间还得 @1dot75cm )

**Comment by 1dot75cm** [comment]
内测完成，大家可以上去编包测试了。

**Comment by cheese** [comment]
厉害！
