### ISSUE TITLE
[RFC]中文社区Copr打包分类指南

### ISSUE THREAD

**Issue by sztsian** [FZUG/Copr#5]
https://github.com/FZUG/Copr/wiki/%E4%B8%AD%E6%96%87%E7%A4%BE%E5%8C%BACopr%E6%89%93%E5%8C%85%E5%88%86%E7%B1%BB%E6%8C%87%E5%8D%97
我起草了中文社区打包分类指南。现在需要大家评论以及完善。

这个Issue的目的是完善打包分类指南。当超过半数在 github/FZUG 活跃的人认为不再需要修改后，或者经过一些修改，超过10天没有新的完善意见后，可以视为已解决进行关闭。

**Comment by sztsian** [comment]
@alick9188

**Comment by tvvocold** [comment]
@FZUG/tier1 @FZUG/owners

**Comment by alick9188** [comment]
感谢 @sztsian 。我做了一些修改，请各位过目。

另外，关于情形5的“书面许可”，指的是什么？邮件算吗？我觉得可以把邮件作为许可凭证。

**Comment by sztsian** [comment]
@alick9188 考虑到国内法律，电子邮件的法律地位仍不足，我不主张使用电子邮件作为凭证。但可以考虑接受电子邮件形式发送的授权文件扫描件，以及经过国内相关政府机构认可的数字签名过的授权文件电子版。不过这两者太具体，因而我没有列出来。

**Comment by Endle** [comment]
个人觉得，456类的软件定义不是很清晰。大家怎么看呢？

**Comment by alick9188** [comment]
@sztsian OK. 我觉得需要列出来，越具体越利于执行。可以不写在正文里，最后加个补充说明的段落。

**Comment by sztsian** [comment]
@Endle 诚然，我也只是个工科男，驾驭文字的能力有限。不过我觉得其实IT领域很多东西界限本身就很模糊，因而不如随着工作的发展，逐步细化4、5、6的具体说明？
此外我觉得4是明确的。就是没有选择许可证的开源软件，和，采用 CDDL等（允许分发的但许可证本身有争议的）许可证的软件

**Comment by Endle** [comment]
> @Endle 诚然，我也只是个工科男，驾驭文字的能力有限。
不太赞同。我们现在在触及法律问题，相关的逻辑必须清楚（所以，工科男应该更有优势？2333）

> 不过我觉得其实IT领域很多东西界限本身就很模糊，
如果是大公司，可以游走在灰色地带，然后有问题了，找一个律师团队
但我们是社区，就必须明哲保身

> 因而不如随着工作的发展，逐步细化4、5、6的具体说明？
我赞同迭代逐步细化，但我们最初的版本一定要足够严格
不然，以后出了问题，某人说，“我的行为符合社区在2015年3月通过的第一版的指南”，我们应该如何处理？
同样，大公司可以隔几天发一封邮件“我们修改了xxx协议”，然后把问题扔给律师，但我们不行

> 此外我觉得4是明确的。就是没有选择许可证的开源软件，和，采用 CDDL等（允许分发的但许可证本身有争议的）许可证的软件
我不觉得 4 是明确的

**Comment by Endle** [comment]
我的提议：站在巨人的肩膀上，使用 OSI-approved 的概念 [认证的协议列表](http://opensource.org/licenses/alphabetical)

如果一个软件没有使用被认证的协议，那我们暂时先不要碰这个东西为好

另外，最好注明，被打包的软件要符合中华人民共和国的法律，例如
> Please be aware that you are legally responsible for all of your contributions, edits, and re-use of Wikimedia content under the laws of the United States of America and other applicable laws (which may include the laws where you live or where you view or edit content). 

摘录自 <http://wikimediafoundation.org/wiki/Terms_of_Use>

**Comment by tvvocold** [comment]
FYI:
官方是这样[泛规定的](https://fedorahosted.org/copr/wiki/UserDocs#WhatIcanbuildinCopr)
其中指明要打包者自行承担检查 License 的责任，并提供了举报滥用行为的[Feature](https://copr.fdzh.org/coprs/mosquito/kernel/legal_flag).

PS: 
显然这个举报功能又挂了,@1dot75cm

**Comment by sztsian** [comment]
> 我的提议：站在巨人的肩膀上，使用 OSI-approved 的概念 认证的协议列表

OSI Approved只有71种，[Fedora Licensing](https://fedoraproject.org/wiki/Licensing:Main) 有263行，因此我暂时不能直接采用OSI Approved作为标准。
>如果一个软件没有使用被认证的协议，那我们暂时先不要碰这个东西为好

这点怕是还有争议。github上很多自由软件都是许可证不明确的，或者是采用的没有被认证的许可证。因此我觉得单论这点来说，不应该作为一刀切的依据。应该再细化。
>另外，最好注明，被打包的软件要符合中华人民共和国的法律。

谢谢。已添加。

>>此外我觉得4是明确的。就是没有选择许可证的开源软件，和，采用 CDDL等（允许分发的但许可证本身有争议的）许可证的软件

>我不觉得 4 是明确的

呃。对于第四条，看起来还需要再清晰一些。
但同样存在一个问题，此前这个问题也颇具争议：如果本地Copr只能打包严格的符合自由与开源软件许可证的软件，那这样就完全没有存在的意义了，因为现有的源基本能够涵盖这些软件了，我们所需的就只是向对应的源推送了。因而在做这个分类指南的时候，根据线下活动中与不同人员的讨论，我们觉得可以放宽至：符合法律，是自由软件，容许它没有明确的许可证。

**Comment by Endle** [comment]
@sztsian commented on [2015年3月14日 GMT+8下午11:19](https://github.com/FZUG/Copr/issues/5#issuecomment-80529866 "2015-03-14T15:19:25Z - Replied by Github Comment Enhancer"):
> > 我的提议：站在巨人的肩膀上，使用 OSI-approved 的概念 认证的协议列表
> 
> OSI Approved只有71种，[Fedora Licensing](https://fedoraproject.org/wiki/Licensing:Main) 有263行，因此我暂时不能直接采用OSI Approved作为标准。

是说 OSI Approved 范围太窄吗？我觉得，我们可以先采用一个比较小的范围，然后再逐步扩充，这样风险小

> >如果一个软件没有使用被认证的协议，那我们暂时先不要碰这个东西为好
> 
> 这点怕是还有争议。github上很多自由软件都是许可证不明确的，或者是采用的没有被认证的许可证。因此我觉得单论这点来说，不应该作为一刀切的依据。应该再细化。

支持进一步细化

> >>此外我觉得4是明确的。就是没有选择许可证的开源软件，和，采用 CDDL等（允许分发的但许可证本身有争议的）许可证的软件
> 
> >我不觉得 4 是明确的
> 
> 呃。对于第四条，看起来还需要再清晰一些。
> 但同样存在一个问题，此前这个问题也颇具争议：如果本地Copr只能打包严格的符合自由与开源软件许可证的软件，那这样就完全没有存在的意义了，因为现有的源基本能够涵盖这些软件了，我们所需的就只是向对应的源推送了。因而在做这个分类指南的时候，根据线下活动中与不同人员的讨论，我们觉得可以放宽至：符合法律，是自由软件，容许它没有明确的许可证。

基本赞同。我个人的建议是，放宽对非自由的软件的限制。
例如，（仅仅是假设），如果我们得到了重分发WPS的授权，那是否可以推送呢？我认为是可以的。一个软件没有明确的 LICENSE，但我们找到了所有者，并拿到了书面授权，那为什么不重分发呢？进一步讲，通过研究EULA，发现某个程序可以重分发，那我们也可以推送到源中。

但在模糊地带，我们还是小心点为好。如有必要，可以逐步放宽要求

**Comment by tvvocold** [comment]
谨慎为佳，参考[suse的打包黑名单](https://zh.opensuse.org/openSUSE:Build_Service_application_blacklist)
`其他的软件可以考虑（通过邮件列表）申请纳入到 Non-Free 源 `
`如果你想打包一个非自由软件包，请提交包含有关的分发许可证和供应商信息的 bug 报告。`

**Comment by 1dot75cm** [comment]
引用的部分加上外链接，举一些相关例子，然后我觉得就可以了。
每个项目都需要在主页添加软件授权协议说明，github链接（如果有）；如果是开发人员测试打包，那么注明测试即可。由社区人员进行项目审查，举报滥用行为。

**Comment by sztsian** [comment]
>>> 我的提议：站在巨人的肩膀上，使用 OSI-approved 的概念 认证的协议列表

>> OSI Approved只有71种，[Fedora Licensing](https://fedoraproject.org/wiki/Licensing:Main) 有263行，因此我暂时不能直接采用OSI Approved作为标准。

>是说 OSI Approved 范围太窄吗？我觉得，我们可以先采用一个比较小的范围，然后再逐步扩充，这样风险小

可能这是当前争论的核心所在。我比较主张根据Fedora Licensing进行进一步完善。OSI Approved太小了恐怕不利于吸引打包者

>>>如果一个软件没有使用被认证的协议，那我们暂时先不要碰这个东西为好

>> 这点怕是还有争议。github上很多自由软件都是许可证不明确的，或者是采用的没有被认证的许可证。因此我觉得单论这点来说，不应该作为一刀切的依据。应该再细化。

>支持进一步细化

>>>>此外我觉得4是明确的。就是没有选择许可证的开源软件，和，采用 CDDL等（允许分发的但许可证本身有争议的）许可证的软件
 
>>>我不觉得 4 是明确的

>> 呃。对于第四条，看起来还需要再清晰一些。
>> 但同样存在一个问题，此前这个问题也颇具争议：如果本地Copr只能打包严格的符合自由与开源软件许可证的软件，那这样就完全没有存在的意义了，因为现有的源基本能够涵盖这些软件了，我们所需的就只是向对应的源推送了。因而在做这个分类指南的时候，根据线下活动中与不同人员的讨论，我们觉得可以放宽至：符合法律，是自由软件，容许它没有明确的许可证。

>基本赞同。我个人的建议是，放宽对非自由的软件的限制。
例如，（仅仅是假设），如果我们得到了重分发WPS的授权，那是否可以推送呢？我认为是可以的。一个软件没有明确的 LICENSE，但我们找到了所有者，并拿到了书面授权，那为什么不重分发呢？进一步讲，通过研究EULA，发现某个程序可以重分发，那我们也可以推送到源中。

这个观点我完全认同。至于4、5两点，是我在起草这个方案的时候临时拆分的（此前线下我们更多的讨论认为是5点，1.2.3.6与此前下线下讨论的完全一致，4.5是将线下讨论结果进一步细化的结果。看起来这个细化做的不够理想。此前对于4这个情况是与5一样认为必须是作者主动提出打包需要并授权打包及分发）

>但在模糊地带，我们还是小心点为好。如有必要，可以逐步放宽要求

+1

**Comment by sztsian** [comment]
> 谨慎为佳，可以参考[suse的禁止软件](https://zh.opensuse.org/openSUSE:Build_Service_application_blacklist)
`其他的软件可以考虑（通过邮件列表）申请纳入到 Non-Free 源 `
`如果你想打包一个非自由软件包，请提交包含有关的分发许可证和供应商信息的 bug 报告。`

OK,参考OSI Approved列表，以及Fedora关于打包的规范。

>特别需要注意下，[代码还是数据内容](https://zh.opensuse.org/openSUSE:Packaging_guidelines#.E4.BB.A3.E7.A0.81.E8.BF.98.E6.98.AF.E6.95.B0.E6.8D.AE.E5.86.85.E5.AE.B9)，这点正是我们忽略的（suse把规则分三点：禁止的软件，授权许可，数据内容。这样很清晰的解决了问题，并且配备法律团队）

感谢提醒。我当前主要关注了代码，没有关注“数据内容”

>我个人意见：
1，既然是练习场，就不能因为软件满足了 “1，符合 Fedora 打包规范” 就不能在中文 Copr 上打包
2，加入数据内容规范
3，打包一个非自由软件>请联系作者申请并允许公开许可（至于 许可 以邮件形式是否妥当/合法，这点还需讨论）
4，加入免责（打包者自行承担检查 License 的责任，并提供了举报滥用行为的 Feature）
5，最好请社区内有相关法律经验的人来进一步完善。

1应该是已经修正过了。2可以参考openSUSE的，稍后谁有时间完善下？3我觉得要求公开许可。4稍后应当添加到指南 5看起来社区没有搞法律的人。。。

**Comment by sztsian** [comment]
> 引用的部分加上外链接，举一些相关例子，然后我觉得就可以了。
每个项目都需要在主页添加软件授权协议说明，github链接（如果有）；如果是开发人员测试打包，那么注明测试即可。由社区人员进行项目审查，举报滥用行为。

不知道copr是否有tag功能。

**Comment by tvvocold** [comment]
@sztsian 
恩，可以直接写入 [FAQ](https://github.com/FZUG/Copr/wiki/FAQ)
Copr 没有 Tag 功能。（不过举报功能已测试成功）
另外，本 Issue 可以 Close 掉了?

**Comment by sztsian** [comment]
@tvvocold 
还不能关。还没完善好。
@alick9188  对于第三条我有了一些修改，还需要大家看看。
此外，我个人认为数据内容貌似没有必要允许在中文社区Copr中打包。但附加在自由软件程序中的必备的符合自由软件许可证的数据内容（如软件界面的图标等）除外。

**Comment by sztsian** [comment]
中英文空格问题，我当前采取，对除了“中文社区Copr”之外的其他位置均加空格。“中文社区Copr” 只在Copr后加了空格。

**Comment by alick** [comment]
> 对除了“中文社区Copr”之外的其他位置均加空格。“中文社区Copr” 只在Copr后加了空格。

这样还是不一致

**Comment by sztsian** [comment]
@alick done again. Pls review

**Comment by alick** [comment]
@sztsian I have no further comments.

**Comment by sztsian** [comment]
I will close this and remove the DRAFT sign if no more issue within the next 5 days.

**Comment by sztsian** [comment]
Close this as no more comments
